/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppAiSettingsRouteImport } from './routes/_app/ai-settings'
import { Route as AppAssistantRouteImport } from './routes/_app/assistant'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppBoardRouteImport } from './routes/_app/board'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppChangelogRouteImport } from './routes/_app/changelog'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppFilesRouteImport } from './routes/_app/files'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppPromptsRouteImport } from './routes/_app/prompts'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppCustomersIdRouteImport } from './routes/_app/customers_.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAiSettingsRoute = AppAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppChangelogRoute = AppChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers_/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AppAccountRoute
  '/activity': typeof AppActivityRoute
  '/ai-settings': typeof AppAiSettingsRoute
  '/assistant': typeof AppAssistantRoute
  '/billing': typeof AppBillingRoute
  '/board': typeof AppBoardRoute
  '/calendar': typeof AppCalendarRoute
  '/changelog': typeof AppChangelogRoute
  '/customers': typeof AppCustomersRoute
  '/files': typeof AppFilesRoute
  '/integrations': typeof AppIntegrationsRoute
  '/invoices': typeof AppInvoicesRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRoute
  '/products': typeof AppProductsRoute
  '/projects': typeof AppProjectsRoute
  '/prompts': typeof AppPromptsRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/tickets': typeof AppTicketsRoute
  '/customers/$id': typeof AppCustomersIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/account': typeof AppAccountRoute
  '/activity': typeof AppActivityRoute
  '/ai-settings': typeof AppAiSettingsRoute
  '/assistant': typeof AppAssistantRoute
  '/billing': typeof AppBillingRoute
  '/board': typeof AppBoardRoute
  '/calendar': typeof AppCalendarRoute
  '/changelog': typeof AppChangelogRoute
  '/customers': typeof AppCustomersRoute
  '/files': typeof AppFilesRoute
  '/integrations': typeof AppIntegrationsRoute
  '/invoices': typeof AppInvoicesRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRoute
  '/products': typeof AppProductsRoute
  '/projects': typeof AppProjectsRoute
  '/prompts': typeof AppPromptsRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/tickets': typeof AppTicketsRoute
  '/': typeof AppIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/ai-settings': typeof AppAiSettingsRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/board': typeof AppBoardRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/changelog': typeof AppChangelogRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/files': typeof AppFilesRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/prompts': typeof AppPromptsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/customers_/$id': typeof AppCustomersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/account'
    | '/activity'
    | '/ai-settings'
    | '/assistant'
    | '/billing'
    | '/board'
    | '/calendar'
    | '/changelog'
    | '/customers'
    | '/files'
    | '/integrations'
    | '/invoices'
    | '/notifications'
    | '/orders'
    | '/products'
    | '/projects'
    | '/prompts'
    | '/reports'
    | '/roles'
    | '/search'
    | '/settings'
    | '/team'
    | '/tickets'
    | '/customers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/account'
    | '/activity'
    | '/ai-settings'
    | '/assistant'
    | '/billing'
    | '/board'
    | '/calendar'
    | '/changelog'
    | '/customers'
    | '/files'
    | '/integrations'
    | '/invoices'
    | '/notifications'
    | '/orders'
    | '/products'
    | '/projects'
    | '/prompts'
    | '/reports'
    | '/roles'
    | '/search'
    | '/settings'
    | '/team'
    | '/tickets'
    | '/'
    | '/customers/$id'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/account'
    | '/_app/activity'
    | '/_app/ai-settings'
    | '/_app/assistant'
    | '/_app/billing'
    | '/_app/board'
    | '/_app/calendar'
    | '/_app/changelog'
    | '/_app/customers'
    | '/_app/files'
    | '/_app/integrations'
    | '/_app/invoices'
    | '/_app/notifications'
    | '/_app/orders'
    | '/_app/products'
    | '/_app/projects'
    | '/_app/prompts'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/tickets'
    | '/_app/'
    | '/_app/customers_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-settings': {
      id: '/_app/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AppAiSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board': {
      id: '/_app/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/changelog': {
      id: '/_app/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AppChangelogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prompts': {
      id: '/_app/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers_/$id': {
      id: '/_app/customers_/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppActivityRoute: typeof AppActivityRoute
  AppAiSettingsRoute: typeof AppAiSettingsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBoardRoute: typeof AppBoardRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChangelogRoute: typeof AppChangelogRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppFilesRoute: typeof AppFilesRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppPromptsRoute: typeof AppPromptsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppActivityRoute: AppActivityRoute,
  AppAiSettingsRoute: AppAiSettingsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppBillingRoute: AppBillingRoute,
  AppBoardRoute: AppBoardRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChangelogRoute: AppChangelogRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppFilesRoute: AppFilesRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProductsRoute: AppProductsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppPromptsRoute: AppPromptsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
