services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql

  valkey:
    image: valkey/valkey:9-alpine
    volumes:
      - valkey_data:/data

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    command: server -s3 -dir=/data
    volumes:
      - seaweedfs_data:/data

volumes:
  postgres_data:
  valkey_data:
  seaweedfs_data:
