[tools]
uv = "latest"

[env]
_.file = ".env"
PORT = { default = "8000" }

[tasks.dev]
run = "uv run uvicorn app.main:app --reload --port $PORT"

[tasks.start]
run = "uv run uvicorn app.main:app --port $PORT"

[tasks.check]
run = ["uv run ruff check .", "uv run ruff format --check ."]

[tasks.check-fix]
run = [
    "uv run ruff check --fix .",
    "uv run ruff format .",
    "uv run ruff check .",
    "uv run ruff format --check .",
]
