services:
  python-inference:
    build: ./inference/python
    ports:
      - "8000:8000"
    environment:
      MODEL_PATH: /models/mnist-8.onnx
    volumes:
      - ./models:/models:ro

  javascript-inference:
    build: ./inference/js
    ports:
      - "8001:8000"
    environment:
      MODEL_PATH: /models/mnist-8.onnx
    volumes:
      - ./models:/models:ro
